### ISSUE TITLE
[BUG] Upgrading to GNOME 46 breaks the extension (version mismatch ?)

### ISSUE THREAD

**Issue by EDM115** [SUPERCILEX/gnome-clipboard-history#166]
This one is a bit special  
I installed the extension on Ubuntu 23.10, so GNOME 45, extension version 40  
After upgrading my Ubuntu to 24.04, the extension was marked as not working. The only way around was to remove it, and then install the correct version (GNOME 46 extension, version 39)

**Comment by SUPERCILEX** [comment]
That's a annoying, but I have no idea what could be the cause, how to fix it, or if that's even something that can be fixed by the extension. :sweat_smile: Also since it's a one-time thing, I'm not going to think about it too hard. Thanks for the bug report though!

**Comment by artemudovyk** [comment]
For me it said `TypeError: hbox.add is not a function` if it would be helpful.

Reinstalled the extension as well, and now it seems ok.

**Comment by SUPERCILEX** [comment]
> For me it said `TypeError: hbox.add is not a function` if it would be helpful to debug.
> 
> Reinstalled the extension as well, and now it seems ok.

Thanks! Here's my theory as to what's happening then. These are the extension versions:
![image](https://github.com/SUPERCILEX/gnome-clipboard-history/assets/9490724/095f1011-0067-4ebf-b3f3-34ce06a64b0a)

I uploaded things in reverse order for whatever reason, so I'm guessing that gnome is refusing to downgrade the extension to the 46 compatible version because it has a lower version code. Really gnome needs extension version codes to be a pair of GNOME version and extension version, but oh well.

I re-uploaded the v39 extension so it gets a higher version code than the gnome 45 extension.

**Comment by EDM115** [comment]
> gnome is refusing to downgrade the extension to the 46 compatible version because it has a lower version code

that's what I supposed on the title with "version mismatch"  
but they behavior is really weird imo
